#应用名称
spring:
  application:
    name: student-hystrix-provider
  #数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.88.104:3306/springcloud
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    #jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #web地址
server:
  port: 4001
  #eureka 客户端配置
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}  #eureka客户端主机实例名称
    instance-id: ${spring.cloud.client.ipAddress}:${server.port} #客户端实例名称
    prefer-ip-address: true #显示Ip
    #lease-renewal-interval-in-seconds: 30 #心跳时间
    #lease-expiration-duration-in-seconds: 30 #服务失效时间
    appname: student-hystrix-provider
  client:
    service-url:
      defaultZone: http://192.168.88.104:3001/eureka/,http://192.168.88.106:3001/eureka/   #把服务注册到eureka注册中心
      #defaultZone: http://localhost1.com:2001/,http://localhost2.com:2002/,http://localhost3.com:2003/
#eureka info 页面
info:
  groupId: ${project.groupId}
  artifactId: ${project.artifactId}
  version: ${project.version}
  provider: ${spring.cloud.client.ipAddress}hystrix-student-provider${server.port}
  number: 15282648585
myinfo:
   name: 熔断服务提供者_${server.port}
#security:
#  user:
#    name: admin
#    password: 1234
##management:
##  security:
##    enabled: false
management:
  security:
    enabled: false
##    roles: admin