#应用名称
spring:
  application:
    name: student-hystrix-provider
  #数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${spring.cloud.client.ipAddress}:3306/springcloud
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    #jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #web地址
eureka:
  instance:
    #hostname:  #主机名，默认操作系统的主机名
    #appname: student-provider  #客户端服务名 默认applicationName
    instance-id: ${spring.application.name}-${spring.cloud.client.ipAddress}:${random.int(500,1000)} #客户端实例名称
    prefer-ip-address: true #显示Ip
    lease-renewal-interval-in-seconds: 30 #心跳时间
    lease-expiration-duration-in-seconds: 60 #服务超时失效时间
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${spring.cloud.client.ipAddress}:3001/eureka/
      #defaultZone: http://192.168.88.104:3001/eureka/,http://192.168.88.106:3001/eureka/   #把服务注册到eureka注册中心
      #defaultZone: http://localhost1.com:2001/,http://localhost2.com:2002/,http://localhost3.com:2003/
#actutor info 页面
info:
  groupId: ${project.groupId}
  artifactId: ${project.artifactId}
  version: ${project.version}
  provider: ${eureka.instance.instance-id}
  number: 15282648585
myinfo:
  name: ${spring.application.name}-${server.port}
#security:
#  user:
#    name: admin
#    password: 1234
##management:
##  security:
##    enabled: false
##    roles: admin
server:
  servlet:
    path: /
  port: 0
management:
  endpoint:
    health:
      enabled: true
    web:
      exposure:
        # spring-boot-starter-actuator 2.0版本以上得这么配置，将接口暴露出来，如果要暴露全部节点使用include: "*"
        include: "*"
