spring:
  application:
    name: eureka_Server2
server:
  port: 3002
eureka:
  instance:
    hostname: eureka_Server2
    # appname: eureka_Server
    prefer-ip-address: true
  client:
    register-with-eureka: false #注册自身
    fetch-registry: false
    service-url:
      defaultZone: http://server1:3001/eureka/,http://server2:3002/eureka/
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #defaultZone: http://localhost1.com:2001/eureka/,http://localhost2.com:2002/eureka/,http://localhost3.com:2003/eureka/
  server:
    enable-self-preservation: false
#eureka info 页面
info:
  groupId: ${project.groupId}
  artifactId: ${project.artifactId}
  version: ${project.version}
  provider: eureka_server3002
  number: 15282648585