spring:
  application:
    name: eureka_Server
server:
  port: 3001
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress} #服务注册中心实例的名字
    # appname: eureka_Server
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    register-with-eureka: false #注册自身
    fetch-registry: false #是否检索服务
    service-url:
        defaultZone: http://${spring.cloud.client.ipAddress}:3001/eureka/
       # defaultZone: http://${spring.cloud.client.ipAddress}:3001/eureka/,http://192.168.88.106:3001/eureka/ #指定服务注册中心位置
    #defaultZone: http://localhost1.com:2001/eureka/,http://localhost2.com:2002/eureka/,http://localhost3.com:2003/eureka/
  server:
    enable-self-preservation: false #保护机制关闭
#eureka info 页面
info:
  groupId: ${project.groupId}
  artifactId: ${project.artifactId}
  version: ${project.version}
  provider: ${spring.cloud.client.ipAddress}_eureka_server_${server.port}
  number: 15282648585
management:
  security:
    enabled: false