#应用名称
spring:
  application:
    name: student-provider
  #数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${spring.cloud.client.ipAddress}:3306/springcloud
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    #jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #web地址
server:
  port: 0
  #eureka 客户端配置
eureka:
  instance:
    #hostname:  #主机名，默认操作系统的主机名
    #appname: student-provider  #客户端服务名 默认applicationName
    instance-id: ${spring.application.name}.${spring.cloud.client.ipAddress}:${random.int(1,500)} #客户端实例名称(status)
    prefer-ip-address: true #优先使用Ip地址为主机标识
    lease-renewal-interval-in-seconds: 30 #心跳时间
    lease-expiration-duration-in-seconds: 60 #服务超时失效时间
  client:
    service-url:
      defaultZone: http://${spring.cloud.client.ipAddress}:3001/eureka/
      #defaultZone: http://${spring.cloud.client.ipAddress}:3001/eureka/,http://192.168.88.106:3001/eureka/   #把服务注册到eureka注册中心
    fetch-registry: true #获取服务实例清单
    register-with-eureka: true #向eureka注册自己
    registry-fetch-interval-seconds: 20 #获取清单间隔时间
    enabled: true #启用eureka客户端
    instance-info-replication-interval-seconds: 30 #更新实例变化到eureka服务端的间隔时间
    initial-instance-info-replication-interval-seconds: 40 #初始化实例到eureka服务端的间隔时间
    eureka-service-url-poll-interval-seconds: 300 #轮训eureka服务端地址更改的间隔时间（配合springcloud config）
    filter-only-up-instances: true #获取实例时，仅仅保存up状态的实例
#actutor info 页面
info:
  groupId: ${project.groupId}
  artifactId: ${project.artifactId}
  version: ${project.version}
  provider: ${eureka.instance.instance-id}
  number: 15282648585
myInfo:
   name: ${spring.application.name}_${server.port}
management:
  security:
    enabled: false