#应用名称
spring:
  application:
    name: student-provider
  #数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.88.104:3306/springcloud
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    #jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  #web地址
server:
  port: 1001
  #eureka 客户端配置
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}  #eureka客户端主机实例名称
    #appname: student-provider  #客户端服务名 默认applicationName
    instance-id: ${spring.cloud.client.ipAddress}:${server.port} #客户端实例名称
    prefer-ip-address: true #显示Ip
    lease-renewal-interval-in-seconds: 30 #心跳时间
    lease-expiration-duration-in-seconds: 30 #服务失效时间
  client:
    service-url:
      defaultZone: http://192.168.88.104:3001/eureka/,http://192.168.88.106:3001/eureka/   #把服务注册到eureka注册中心
    healthcheck:
      enabled: true
#eureka info 页面
info:
  groupId: ${project.groupId}
  artifactId: ${project.artifactId}
  version: ${project.version}
  provider: ${spring.cloud.client.ipAddress}_student-provider_${server.port}
  number: 15282648585
myInfo:
   name: provider_ ${server.port}
management:
  security:
    enabled: false