spring:
  application:
    name: student-consumer
server:
  port: 80
  context-path: /
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}  #eureka客户端主机实例名称
    #appname: student-consumer  #客户端服务名
    instance-id: ${spring.application.name}-${spring.cloud.client.ipAddress}:${server.port} #客户端实例名称
    prefer-ip-address: true #显示IP
  client:
    fetch-registry: true #获取服务实例清单
    register-with-eureka: true #向eureka注册自己
    registry-fetch-interval-seconds: 20 #获取清单间隔时间
    service-url:
      #defaultZone: http://${spring.cloud.client.ipAddress}:3001/eureka/  #本地server
      defaultZone: http://192.168.88.104:3001/eureka/,http://192.168.88.106:3001/eureka/   #把服务注册到eureka注册中心 集群
#actutor info 页面
info:
  groupId: ${project.groupId}
  artifactId: ${project.artifactId}
  version: ${project.version}
  provider: ${eureka.instance.instance-id}
  number: 15282648585
appLoaction: http://student-provider
management:
  security:
    enabled: false