spring:
  application:
    name: student-consumer
server:
  port: 80
  context-path: /
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}  #eureka客户端主机实例名称
    #appname: student-consumer  #客户端服务名
    instance-id: ${spring.cloud.client.ipAddress}:${server.port} #客户端实例名称
    prefer-ip-address: true #显示IP
  client:
    service-url:
      defaultZone: http://192.168.88.104:3001/eureka/,http://192.168.88.106:3001/eureka/   #把服务注册到eureka注册中心
      #defaultZone: http://localhost1.com:2001/,http://localhost2.com:2002/,http://localhost3.com:2003/
#eureka info 页面
info:
  groupId: ${project.groupId}
  artifactId: ${project.artifactId}
  version: ${project.version}
  provider: ${spring.cloud.client.ipAddress}_hystrix-consumer_${server.port}
  number: 15282648585
appLoaction: http://student-hystrix-provider
management:
  security:
    enabled: false
